# Generated by Django 3.2.9 on 2021-12-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_url_is_crawled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='output_type',
            field=models.CharField(choices=[('html', 'Textual Data'), ('pdf', 'PDF')], max_length=20),
        ),
    ]
